import discord
from discord import app_commands
from discord.ext import commands
from utils import config, is_whitelisted
import random
import string
import os

class PremiumKey(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.keys_file = "resources/premium_key.txt"
        
        if not os.path.exists(self.keys_file):
            with open(self.keys_file, 'w') as f:
                pass

    def generate_key(self) -> str:
        chars = string.ascii_uppercase + string.digits
        return ''.join(random.choice(chars) for _ in range(8))

    def save_key(self, key: str):
        with open(self.keys_file, 'a') as f:
            f.write(f"{key}\n")

    @app_commands.command(name="premium_key", description="Generate a premium key")
    @is_whitelisted()
    async def premium_key(self, interaction: discord.Interaction):
        if str(interaction.user.id) not in config['whitelist']:
            embed = discord.Embed(
                title="❌ Error",
                description="> ⛔ You don't have permission to generate premium keys!",
                color=int(config['colors']['error'], 16)
            )
            embed.set_footer(text=f"Executed by {interaction.user} | gxqk the best", icon_url=interaction.user.display_avatar.url)
            await interaction.response.send_message(embed=embed, ephemeral=True)
            return

        key = self.generate_key()
        
        self.save_key(key)
        
        embed = discord.Embed(
            title="🎟️ Premium Key Generated",
            description=f"> 🔑 Here's your premium key: `{key}`\n\n> ⚠️ This key is single-use and can only be used once.",
            color=int(config['colors']['success'], 16),
            timestamp=discord.utils.utcnow()
        )
        embed.set_footer(text=f"Generated by {interaction.user} | gxqk the best", icon_url=interaction.user.display_avatar.url)
        
        await interaction.response.send_message(embed=embed, ephemeral=True)

async def setup(bot: commands.Bot):
    await bot.add_cog(PremiumKey(bot)) 